services:
  xtb-bot:
    build:
      context: .
      args:
        FE_PORT: ${FE_PORT}
        BE_PORT: ${BE_PORT}
    ports:
      - "${FE_PORT}:${FE_PORT}"
      - "${BE_PORT}:${BE_PORT}"
    volumes:
      - .:/app
      - node_modules_docker:/app/node_modules
    env_file: .env

volumes:
  node_modules_docker:
